### ISSUE TITLE
ffmpeg has json output

### ISSUE THREAD

**Issue by phiresky** [harryjackson/ffmpeg_split#2]
Just as a note, you could use the integrated json output format of ffmpeg to make the code simpler and more robust. Example:

```ffprobe -i fname -print_format json -show_chapters -loglevel error```

```json
{
    "chapters": [
        {
            "id": 2072203953,
            "time_base": "1/1000000000",
            "start": 0,
            "start_time": "0.000000",
            "end": 2622000000,
            "end_time": "2.622000",
            "tags": {
                "title": "(Unnamed scene)"
            }
        },
        {
            "id": 675085945,
            "time_base": "1/1000000000",
            "start": 2622000000,
            "start_time": "2.622000",
            "end": 88622000000,
            "end_time": "88.622000",
            "tags": {
                "title": "(Unnamed scene)"
            }
        },
...
```

**Comment by harryjackson** [comment]
I've updated the question on stackoverflow with your information. If you have a stackoverflow profile I could add it to the answer.

https://stackoverflow.com/questions/30305953/is-there-an-elegant-way-to-split-a-file-by-chapter-using-ffmpeg/
